### MAJOR PROJECT

# Sales Data Reconciliation & Revenue Validation Analysis

In [84]:
# libraries 
import pandas as pd
import numpy as np

In [85]:
import sys
sys.executable

'C:\\Users\\pasal\\anaconda3\\python.exe'

## load the dataset

In [86]:
import os
os.getcwd()

'C:\\Users\\pasal'

In [122]:
orders = pd.read_csv("olist_orders_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
payments = pd.read_csv("olist_order_payments_dataset.csv")
customers = pd.read_csv("olist_customers_dataset.csv")

In [123]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [88]:
order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,19-09-2017 09:45,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,03-05-2017 11:05,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,18-01-2018 14:48,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,15-08-2018 10:10,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,13-02-2017 13:57,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,02-05-2018 04:11,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,20-07-2018 04:31,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,30-10-2017 17:14,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,21-08-2017 00:04,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,12-06-2018 17:10,43.00,12.79

In [89]:
payments

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [124]:
customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

## Data Understanding

In [90]:
#Shape
order_items.shape

(112650, 7)

In [91]:
payments.shape

(103886, 5)

In [125]:
orders.shape

(99441, 8)

In [126]:
customers.shape

(99441, 5)

In [127]:
#Data Types
orders.info()
print("==================================================")
order_items.info()
print("==================================================")
payments.info()
print("==================================================")
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [128]:
#Missing Values
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [129]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [94]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [130]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

## Checking Granularity

In [95]:
# In order_items: Do you see multiple rows per order? 
order_items['order_id'].value_counts().head(10) #or

order_id
8272b63d03f5f79c56e9e4120aec44ef    21
1b15974a0141d54e36626dca3fdc731a    20
ab14fdcfbe524636d65ee38360e22ce8    20
9ef13efd6949e4573a18964dd1bbe7f5    15
428a2f660dc84138d969ccd69a0ab6d5    15
9bdc4d4c71aa1de4606060929dee888c    14
73c8ab38f07dc94389065f7eba4f297a    14
37ee401157a3a0b28c9c6d0ed8c3b24b    13
2c2a19b5703863c908512d135aa6accc    12
c05d6a79e55da72ca780ce90364abed9    12
Name: count, dtype: int64

In [96]:
order_items.groupby('order_id').size().sort_values(ascending = False)

order_id
8272b63d03f5f79c56e9e4120aec44ef    21
1b15974a0141d54e36626dca3fdc731a    20
ab14fdcfbe524636d65ee38360e22ce8    20
9ef13efd6949e4573a18964dd1bbe7f5    15
428a2f660dc84138d969ccd69a0ab6d5    15
                                    ..
5a0911d70c1f85d3bed0df1bf693a6dd     1
5a082b558a3798d3e36d93bfa8ca1eae     1
5a07264682e0b8fbb3f166edbbffc6e8     1
5a071192a28951b76774e5a760c8c9b7     1
fffe41c64501cc87c801fd61db3f6244     1
Length: 98666, dtype: int64

In [97]:
# In Payments: Do you see multiple rows per order? 
payments.groupby('order_id').size().sort_values(ascending = False).head(10)

order_id
fa65dad1b0e818e3ccc5cb0e39231352    29
ccf804e764ed5650cd8759557269dc13    26
285c2e15bebd4ac83635ccc563dc71f4    22
895ab968e7bb0d5659d16cd74cd1650c    21
fedcd9f7ccdc8cba3a18defedd1a5547    19
ee9ca989fc93ba09a6eddc250ce01742    19
4bfcba9e084f46c8e3cb49b0fa6e6159    15
21577126c19bf11a0b91592e5844ba78    15
3c58bffb70dcf45f12bdf66a3c215905    14
4689b1816de42507a7d63a4617383c59    14
dtype: int64

## Feature Engineering

## Calculate the Order_Value

In [98]:
#item-level revenue
order_items['total_value'] = order_items['price'] + order_items['freight_value']
order_items['total_value']

0          72.19
1         259.83
2         216.87
3          25.78
4         218.04
           ...
112645    343.40
112646    386.53
112647    116.85
112648     64.71
112649     55.79
Name: total_value, Length: 112650, dtype: float64

## Aggregations

In [99]:
# Expected Revenue per Order
order_value = order_items.groupby('order_id')['total_value'].sum().reset_index()

## Calculate Payment Value

In [100]:
# Actual Payment Value per order
payment_value = payments.groupby('order_id')['payment_value'].sum().reset_index()

##  Reconciliation

## Merge Both

In [101]:
df = order_value.merge(payment_value, on = 'order_id', how = 'inner')
df

                               order_id  total_value  payment_value
0      00010242fe8c5a6d1ba2dd792cb16214        72.19          72.19
1      00018f77f2f0320c557190d7a144bdd3       259.83         259.83
2      000229ec398224ef6ca0657da4fc703e       216.87         216.87
3      00024acbcdf0a6daa1e931b038114c75        25.78          25.78
4      00042b26cf59d7ce69dfabb4e55b4fd9       218.04         218.04
...                                 ...          ...            ...
98660  fffc94f6ce00a00581880bf54a75a037       343.40         343.40
98661  fffcd46ef2263f404302a634eb57f7eb       386.53         386.53
98662  fffce4705a9662cd70adb13d4a31832d       116.85         116.85
98663  fffe18544ffabc95dfada21779c9644f        64.71          64.71
98664  fffe41c64501cc87c801fd61db3f6244        55.79          55.79

[98665 rows x 3 columns]

In [102]:
## Calculate Difference
df['difference'] = (df['total_value'] - df['payment_value']).round(2)
df['difference']

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
98660    0.0
98661    0.0
98662    0.0
98663    0.0
98664    0.0
Name: difference, Length: 98665, dtype: float64

In [103]:
## Mismatch Identification
df[df['difference'] != 0]

,order_id,total_value,payment_value,difference
134,005d9a5423d47281ac463a968b3936fb,145.25,145.26,-0.01
165,00789ce015e7e5791c7914f32bb4fad4,168.83,190.81,-21.98
525,016726239765c18f66826453f39c64e3,235.13,265.77,-30.64
724,01e51b7c3025655646143d09b911e1d7,33.10,35.02,-1.92
965,028aa7c930356788f861ed1b7f984819,57.53,62.94,-5.41
...,...,...,...,...
97656,fd571ab12e8d263eaf309774eedfcfeb,948.70,948.69,0.01
97808,fdb034f444a32838124d8907e443d249,31.38,33.56,-2.18
97992,fe35e99a6a5d4d036bf8167d364e0792,262.60,262.59,0.01
98219,fecb65750b4fe05b8257f650b2e114a2,216.76,216.75,0.01
98554,ffb18bf111fa70edf316eb0390427986,617.25,617.24,0.01

In [104]:
df['difference'].value_counts()

difference
 0.00     98089
 0.01       170
-0.01       103
-0.02        20
 0.02        16
          ...
-7.49         1
-3.19         1
-4.23         1
-9.80         1
 21.80        1
Name: count, Length: 255, dtype: int64

## Segmentation

In [105]:
# Categorize
# Clean Data
def categorize(x):
    if abs(x) <= 0.5:
        return 'Match'
    elif x > 0:
        return 'Underpaid'
    else:
        return 'Overpaid'

df['category'] = df['difference'].apply(categorize)

In [106]:
df.head()

,order_id,total_value,payment_value,difference,category
0,00010242fe8c5a6d1ba2dd792cb16214,72.19,72.19,0.0,Match
1,00018f77f2f0320c557190d7a144bdd3,259.83,259.83,0.0,Match
2,000229ec398224ef6ca0657da4fc703e,216.87,216.87,0.0,Match
3,00024acbcdf0a6daa1e931b038114c75,25.78,25.78,0.0,Match
4,00042b26cf59d7ce69dfabb4e55b4fd9,218.04,218.04,0.0,Match

In [107]:
#Count summary
df['category'].value_counts()

category
Match        98410
Overpaid       237
Underpaid       18
Name: count, dtype: int64

# KPI / Percentage Analysis

In [108]:
# insight generation
df['category'].value_counts(normalize=True) * 100

category
Match        99.741550
Overpaid      0.240207
Underpaid     0.018244
Name: proportion, dtype: float64

### Insight:
#### 99.74% of orders are correctly matched, 
#### while 0.26% show discrepancies, 
#### indicating a small but critical issue.

# Data Completeness Check(LEFT JOIN + null check)

In [109]:
# Orders without payments
order_value.merge(payment_value, on='order_id', how='left').isnull().sum()

order_id         0
total_value      0
payment_value    1
dtype: int64

In [110]:
# Payments without orders
payment_value.merge(order_value, on='order_id', how='left').isnull().sum()

order_id           0
payment_value      0
total_value      775
dtype: int64

## ROOT CAUSE ANALYSIS :WHY are these mismatches happening?

In [111]:
problem_df = df[df['category'] != 'Match']
problem_df.head()

,order_id,total_value,payment_value,difference,category
165,00789ce015e7e5791c7914f32bb4fad4,168.83,190.81,-21.98,Overpaid
525,016726239765c18f66826453f39c64e3,235.13,265.77,-30.64,Overpaid
724,01e51b7c3025655646143d09b911e1d7,33.10,35.02,-1.92,Overpaid
965,028aa7c930356788f861ed1b7f984819,57.53,62.94,-5.41,Overpaid
1123,02f4dd90ba0feb8ec394cac05862d2b5,130.96,141.65,-10.69,Overpaid

In [113]:
# find reson for single order
problem_df.iloc[0]['order_id']

'00789ce015e7e5791c7914f32bb4fad4'

In [114]:
order_items[order_items['order_id'] == order_id]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_value
185,00789ce015e7e5791c7914f32bb4fad4,1,f9d774a1820f792952eea079a40a7c6b,2709af9587499e95e803a6498a5a56e9,04-07-2017 23:43,154.0,14.83,168.83

In [115]:
payments[payments['order_id'] == order_id]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
97517,00789ce015e7e5791c7914f32bb4fad4,1,credit_card,10,190.81

In [117]:
payments[['payment_type','payment_installments']].value_counts()

payment_type  payment_installments
credit_card   1                       25455
boleto        1                       19784
credit_card   2                       12413
              3                       10461
              4                        7098
voucher       1                        5775
credit_card   10                       5328
              5                        5239
              8                        4268
              6                        3920
              7                        1626
debit_card    1                        1529
credit_card   9                         644
              12                        133
              15                         74
              18                         27
              11                         23
              24                         18
              20                         17
              13                         16
              14                         15
              17                          8
              16                          5
              21                          3
not_defined   1                           3
credit_card   0                           2
              22                          1
              23                          1
Name: count, dtype: int64

# Mismatch vs Match

In [118]:
## Mismatched orders tend to have higher payment installments
problem_df.merge(payments, on='order_id')['payment_installments'].describe()

count    268.000000
mean       6.011194
std        3.645821
min        1.000000
25%        3.000000
50%        5.000000
75%        8.000000
max       24.000000
Name: payment_installments, dtype: float64

In [120]:
payments.groupby('order_id').size().describe() #normal orders

count    99440.000000
mean         1.044710
std          0.381166
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         29.000000
dtype: float64

In [119]:
## How do normal orders behave in terms of payment installments?
df[df['category'] == 'Match'].merge(payments, on='order_id')['payment_installments'].describe()

count    102788.000000
mean          2.846821
std           2.678689
min           0.000000
25%           1.000000
50%           1.000000
75%           4.000000
max          24.000000
Name: payment_installments, dtype: float64

### Business Insights
 #### Majority of transactions are accurate
 #### Small % of mismatches detected
 #### Overpayments more frequent

### Business Impact
 #### Financial discrepancies
 #### Reporting inaccuracies
 #### Potential revenue leakage

### Recommendations
 #### Monitor installment payments
 #### Add validation checks
 #### Create exception tracking

### Business Conclusion
 #### The analysis confirms that discrepancies are primarily due to installment-based payments, 
 #### which introduce additional charges not reflected in order-level data.